### ISSUE TITLE
HU008:  Log In para pacientes

### ISSUE THREAD

**Issue by yoelvladi** [yoelvladi/BroTel-Inc--Proyecto-Ing-Software#10]
**Yo como:** Cliente
**Quiero:** que los pacientes puedan iniciar sesión con limites en el software
**Para:** que estos puedan acceder a visualizar sus imágenes y citas previas con el cardiólogo.

_Criterio de aceptación:_

* El software cuenta con un inicio de sesión específico para pacientes.
* El inicio de sesión de pacientes limita los permisos y accesos del usuario.
* El inicio de sesión de pacientes les permite acceder a las imágenes y citas previas asociadas a su perfil.

**Comment by BreadMakerMA** [comment]
_Tareas:_

* Desarrollar funcionalidad para inicio de sesión de los pacientes.
* Implementar limitaciones de permisos y accesos a sus perfiles.
* Desarrollar función de acceso a imágenes.
* Desarrollar función de acceso a citas.
* Desarrollar función de búsqueda asociada al perfil en la base de datos.
* Comprobar funcionalidad.

_Estimación:_

* 3 Story points.

**Comment by yoelvladi** [comment]
**Desglose de tareas para el login para pacientes:**

 _Agregar ruta api para poder manejar los métodos del modelo pacientes:_
- Diseñar los métodos para manejar el login dependiendo si es médico o paciente
- Agregar ruta api para hacer la conexión entre el backend y el frontend

 _Modificar el componente de React para manejar el login en el frontend:_
- Agregar una verificación de los permisos
- Agregar una distinción de login dependiendo de los permisos

**Comment by yoelvladi** [comment]
**Avance;** Se crearon los métodos y se agrego una ruta api para conectar el backend y el frontend.
_Tiempo empleado;_
* 1 hora

**Comment by yoelvladi** [comment]
**Avance :** Se modifico el componente React, el cual ahora distingue si es médico o paciente, entregando una vista diferente según sea el usuario.

_Tiempo empleado:_
* 1 hora

**Comment by Benjax052** [comment]
**Avance :** Se agrego archivo para pruebas automaticas.

_Tiempo empleado:_
* 1 hora

**Comment by Benjax052** [comment]
**Avance :** Se modifico el login para utilizar el correo como elemento diferenciador.

_Tiempo empleado:_
* 1 hora

**Comment by Benjax052** [comment]
**Avance :** Modificacion de archivo de prueba para la modificacion del login y se corrieron los test.

_Tiempo empleado:_
* 40 minutos

**Comment by Benjax052** [comment]
### Revisión:
El desarrollo del inicio de sesión para pacientes y la implementación de sus limitaciones de permisos se completaron en aproximadamente 4 horas y 40 minutos, lo que confirma que la estimación original de 3 Story Points fue adecuada. Esta funcionalidad, aunque esencial, presenta una complejidad técnica moderada al requerir manejo de rutas, permisos, y pruebas para garantizar que se ajusta a las restricciones necesarias. Además, las pruebas y ajustes adicionales sugieren que la estimación representa con precisión el esfuerzo y tiempo requeridos.

### Análisis de la Estimación

- Estimación Original: 3 Story Points, basada en la implementación de inicio de sesión, permisos y accesos.

### Trabajo Realizado:

- Backend y conexión API: 1 hora.
- Modificación del componente React: 1 hora.
- Archivo y pruebas automáticas: 1 hora + 40 minutos.
- Ajuste de login con correo: 1 hora.
- Total: ~4 horas y 40 minutos.

### Factores Detectados:

- La implementación fue directa, pero se realizaron pruebas y ajustes adicionales para refinar el comportamiento del login.
- La funcionalidad incluye elementos de seguridad y diferenciación de vistas, esenciales pero no complejos de implementar.

### Conclusión: 
La estimación original de 3 Story Points refleja bien el esfuerzo necesario, considerando el tiempo invertido y la importancia estratégica de la funcionalidad.
