### ISSUE TITLE
HU005: Invertir y hacer zoom a una imagen DICOM

### ISSUE THREAD

**Issue by yoelvladi** [yoelvladi/BroTel-Inc--Proyecto-Ing-Software#7]
**Yo como:** Cardiólogo.
**Quiero:** Poder hacer zoom e invertir los colores de las imágenes.
**Para:** Tener un recurso para distinguir ciertos rasgos de las imágenes cuando considere necesario y útil.

_Criterio de aceptación:_

* Dado que estoy en el software, puedo abrir una imagen DICOM y existe una función que me permite invertir los colores y hacer zoom a las imagenes.
* Dado que se han invertido los colores, existe la opción de restablecer los colores originales.

**Comment by BreadMakerMA** [comment]
_Tareas:_

* Desarrollar función de zoom a la imagen.
* Desarrollar función de inversión de colores.
* Añadir funciones a la interfaz del usuario.
* Implementar opción de restablecimiento
* Comprobar funcionalidad.

_Estimación:_

 * 3 Story points.

**Comment by yoelvladi** [comment]
**Desglose de tareas:**

- Modificar el componente de react para agregar las funciones de invertir colores y hacer zoom a las imagenes.

**Comment by yoelvladi** [comment]
**Avance:**

- Se implemento la función invertir color para la imagen dicom.
- 
_Tiempo empleado:_

- **30 minutos.**

**Comment by yoelvladi** [comment]
**Avance:**

- Se implemento la función de hacer zoom a la imagen dicom

_Tiempo empleado_

- **30 minutos**

**Comment by Benjax052** [comment]
### Revisión:
La implementación de las funcionalidades de zoom e inversión de colores, según el registro, tomó un total de 1 hora (30 minutos por función). Esto indica que ambas tareas tienen baja complejidad técnica y un impacto limitado en el sistema. Además, agregar estas funciones a la interfaz y realizar pruebas no representa un esfuerzo significativo, ya que son operaciones estándar en el manejo de imágenes. Por ello, reducir la estimación a 1 Story Points es razonable y más representativo del esfuerzo real.

### Análisis de la Estimación:

- Estimación Original: Se estimaron 3 Story Points, asumiendo un esfuerzo moderado.

### Trabajo Realizado: 

- Las tareas principales se completaron en 1 hora total, indicando que el esfuerzo requerido fue menor al esperado.

### Factores Clave:

- No surgieron imprevistos técnicos.
- La implementación y pruebas fueron rápidas debido a la simplicidad de las funciones y herramientas disponibles.
### Conclusión: 
La sobreestimación inicial puede deberse a una percepción inflada de la complejidad. El ajuste a 1 Story Point es más acorde al esfuerzo real registrado.
