### ISSUE TITLE
HUU006: Registro de imagenes tomadas

### ISSUE THREAD

**Issue by yoelvladi** [yoelvladi/BroTel-Inc--Proyecto-Ing-Software#9]
**Yo como:** Cardiólogo.
**Quiero:** Tener un registros de pacientes en la base de datos.
**Para:** Mantener un historial de todas las imágenes asociadas a un mismo paciente.

_Criterio de aceptación:_

* Dada una imagen de un paciente, se puede añadir a la base de datos.
* Se puede acceder a las imágenes de un paciente en especifico mediante una base de datos.

**Comment by BreadMakerMA** [comment]
_Tareas:_

* Diseñar la base de datos.
* Desarrollar función añadir imagen.
* Automatizar o añadir función a la interfaz.
* Comprobar funcionalidad.

_Estimación:_

* 5 Story points.

_Importancia:_

* La implementación de un registro histórico y fotográfico de los pacientes es fundamental para el éxito del proyecto, ya que asegura una base sólida para el desarrollo futuro. Este registro no solo permite a los doctores acceder fácilmente a la información médica de sus pacientes, sino que también garantiza la escalabilidad del software al mantener los datos organizados y separados adecuadamente.
* La creación de perfiles bien definidos y estructurados facilita la gestión eficiente de la información, reforzando la arquitectura del sistema y permitiendo futuras expansiones y mejoras. Priorizar esta funcionalidad es esencial, ya que sin ella, otras características como el acceso de los pacientes a las imágenes carecerían de sentido.

**Comment by Benjax052** [comment]
Desglose de tareas función añadir imagen:

_Diseñar la base de datos:_
* Crear tabla de imágenes con columnas ID, Paciente e Imágenes.
* Añadir columna permisos a los usuarios (con el fin de separar a los pacientes de los doctores).

_Desarrollo función añadir imagen:_
* Entregar variable imagen y perfil del paciente al backend.

_Automatizar o añadir función a la interfaz:_
* Automatizar verificar paciente antes de abrir imagen.
* Consultar RUT del paciente; de existir el RUT, asociar.
* De no existir paciente, añadir y crear perfil de paciente.

_Comprobar funcionalidad:_
* Testear función con variable imagen vacía.
* Testear función con perfil vacío.
* Testear función con paciente inexistente.
* Testear función con paciente existente.

**Comment by yoelvladi** [comment]
**Avance** : Las tablas de la base de datos fueron creadas, junto con rutas para manejar las solicitudes del frontend con las tablas

_Tiempo empleado:_
* 2 horas

**Comment by Benjax052** [comment]
**Avance** : Se agrego la función de añadir imagen al DicomViewer, rescatando las variables y la imagen necesaria.

_Tiempo empleado:_
* 2 horas

**Comment by BreadMakerMA** [comment]
**Avance** : Comprobaciones preliminares realizadas; resultados exitosos de momento.

_Tiempo empleado:_
* <1 Hora

**Comment by Benjax052** [comment]
### Revisión
Aunque la implementación inicial registró avances rápidos (aproximadamente 5 horas en total), la estimación de 5 Story Points sigue siendo adecuada debido a la importancia crítica del diseño de la base de datos y las funciones asociadas. Estas tareas no solo demandan un esfuerzo técnico, sino también una validación rigurosa para garantizar integridad, escalabilidad y funcionalidad en diferentes escenarios. Además, la prioridad estratégica de esta funcionalidad justifica mantener su valoración dentro del rango moderado-alto.

### Análisis de la Estimación

- Estimación Original: Se estimaron 5 Story Points, considerando diseño, desarrollo y pruebas.

### Trabajo Realizado:

- Diseño de la base de datos: 2 horas.
- Implementación de añadir imagen: 2 horas.
- Comprobaciones preliminares: <1 hora.
- Total: ~5 horas.

### Factores Detectados:

- El desarrollo avanzó de manera fluida, pero el diseño y validación de la base de datos requerirán atención adicional en futuros ajustes o ampliaciones.
- La funcionalidad implementada es esencial para otras características del sistema, lo que aumenta su relevancia.

### Conclusión:
La estimación fue precisa, reflejando el esfuerzo real necesario. Se confirma que 5 Story Points son representativos del trabajo realizado y su impacto estratégico.
